version: '3.4'
services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/go/src/github.com/parix/grpc-api
  gateway:
    build:
      context: .
      target: gateway
    ports:
      - 8081:8081
  server:
    build:
      context: .
      target: server
