version: '3.4'
services:
  #dev:
  #  build:
  #    context: .
  #    target: dev
  #  volumes:
  #    - .:/go/src/github.com/parix/grpc-api
  gateway:
    build:
      context: .
      target: gateway
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"
  server:
    build:
      context: .
      target: server
    networks:
      envoymesh:
        aliases:
          - echo-api
    expose:
      - "9090"
    environment:
      - GRPC_VERBOSITY=debug

networks:
  envoymesh: {}
