version: '3.4'
services:
  dev:
    build:
      context: .
      target: dev
    volumes:
      - .:/go/src/github.com/parix/grpc-api
  envoy:
    build:
      context: .
      target: envoy
    volumes:
      - ./front-envoy.yaml:/etc/front-envoy.yaml
      - ./api/proto/echo/echo.pb:/tmp/envoy/echo.pb
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "8000:80"
      - "8001:8001"
  server:
    build:
      context: .
      target: server
    networks:
      envoymesh:
        aliases:
          - server
    environment:
      - GRPC_VERBOSITY=debug

networks:
  envoymesh: {}
